# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=108)),
                ('last_name', models.CharField(max_length=108)),
                ('email', models.EmailField(max_length=207)),
                ('mobile_number', models.IntegerField(max_length=18)),
                ('booked_date', models.DateTimeField(verbose_name='date published')),
                ('ip_address', models.CharField(max_length=18)),
                ('message', models.TextField()),
            ],
        ),
    ]
