# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
