# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160610_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booked_date',
            field=models.DateTimeField(verbose_name='date booked'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='mobile_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
