# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160611_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booked_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
