# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160611_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
