# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160611_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_agent',
            field=models.CharField(default='No OS', max_length=250),
        ),
    ]
