# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(unique=True),
        ),
    ]
