# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160613_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointmentstamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 9, 9, 25, 521597, tzinfo=utc), verbose_name='appointment date'),
        ),
    ]
