# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_booking_appointmentstamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointmentstamp',
            field=models.DateTimeField(verbose_name='appointment date'),
        ),
    ]
