# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160614_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.CharField(default='Reliance', max_length=108),
        ),
    ]
