# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_booking_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointmentstamp',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.CharField(max_length=108),
        ),
    ]
