# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160614_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable', models.DateField()),
            ],
        ),
    ]
