# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_disableddates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
