# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160620_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disableddates',
            name='id',
        ),
        migrations.AddField(
            model_name='disableddates',
            name='did',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
