# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160620_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddates',
            name='did',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
