# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20160620_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddates',
            name='disable',
            field=models.DateField(unique=True),
        ),
    ]
