# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20160621_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disableddates',
            old_name='id',
            new_name='did',
        ),
        migrations.AlterField(
            model_name='disableddates',
            name='disable',
            field=models.DateField(),
        ),
    ]
